name: PingMe CI Pipeline

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: java

      - name: Autobuild for CodeQL
        uses: github/codeql-action/autobuild@v4

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4

      - name: Dependency Check (SCA - report only)
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "PingMe"
          path: "."
          format: "HTML"
          out: "dependency-check-report"
        continue-on-error: true

      - name: Upload Dependency Check Report
        if: ${{ hashFiles('dependency-check-report/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report


      - name: Build backend (no tests)
        run: mvn clean package -DskipTests -Dcheckstyle.skip=true

      - name: Run unit tests
        run: mvn test -Dcheckstyle.skip=true -DskipITs

      - name: Set image name
        run: |
          IMAGE_NAME=$(echo "${{ github.repository_owner }}/pingme-backend:ci" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV


      - name: Build Docker image
        env:
          DOCKER_BUILDKIT: 0
        run: docker build -f Dockerfile.backend -t $IMAGE_NAME .

      # üîç Container Image Scan (Trivy)
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_NAME }}
          severity: CRITICAL,HIGH
          exit-code: 0

      
      - name: Run container smoke test
        run: |
          docker run -d -p 8080:8080 --name pingme-test \
            ${{ secrets.DOCKERHUB_USERNAME }}/pingme-backend:ci
          sleep 15
          curl -f http://localhost:8080 || true
          docker stop pingme-test


      #  DockerHub Login
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login \
          -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      #  Push Trusted Image
      - name: Push Docker image
        run: docker push $IMAGE_NAME







